#-------------------------------------------------------------------------------
#
# Prettier Configuration, https://prettier.io/docs/en/configuration.html
#
#-------------------------------------------------------------------------------
---
