#-------------------------------------------------------------------------------
#
# GitHub Actions Test Configuration
#
#-------------------------------------------------------------------------------
---
name: "Test"

on:
  schedule:
    # 11pm UTC (8am Australia/Brisbane)
    - cron: "0 22 * * *"
  pull_request: {}
  push:
    branches:
      - "master"

env:
  CI: true
  CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out code into the Go module directory"
        uses: "actions/checkout@v1"

      - name: "Use Node.js 12.x"
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"

      - name: "Set up Go 1.14"
        uses: "actions/setup-go@v1"
        with:
          go-version: "1.14"
        id: "go"

      - name: "Install"
        run: "yarn install --no-audit && go mod vendor"

      - name: "Lint"
        run: "yarn lint && gofmt -l ./go && gofmt -l ./main.go"

      - name: "Test"
        run: "go test ./go/... -cover -coverprofile=coverage.txt"

      - name: "Publish Coverage"
        run: "bash <(curl -s https://codecov.io/bash)"
        env:
          CODECOV_TOKEN: "${{ secrets. CODECOV_TOKEN }}"
